*** empty log message ***

diff --git a/makefrag b/makefrag
--- a/makefrag
+++ b/makefrag
@@ -1,7 +1,25 @@
 # this file automatically gets inserted into Makefiles generated by opp_makemake
 
 # preserve default target
-all: $(TARGET)
+all: checkdirs $(TARGET)
+
+checkdirs:
+	if [ -d Applications/Ping6]; then \
+	    echo '-----------------------------------------------------------------'; \
+	    echo 'Error: you have empty directories checked out -- please run'; \
+	    echo '"cvs update -dP" to get rid of them, then re-run ./makemake and make.'; \
+	    echo 'Checkout should be done with -P as well: "cvs co -P IPv6SuiteWithINET"'; \
+	    echo '-----------------------------------------------------------------'; \
+	    exit 1; \
+	fi
+	if ! [ -f $(OMNETPP_INCL_DIR)/omnetpp.h ]; then \
+	    echo '-----------------------------------------------------------------'; \
+	    echo 'Error: $(OMNETPP_INCL_DIR) does not have omnetpp.h in it -- your'; \
+	    echo 'omnetppconfig file is probably out of date. Please re-generate it'; \
+	    echo 'with "opp_makemake -f --genconfig omnetppconfig", then run make again.'; \
+	    echo '-----------------------------------------------------------------'; \
+	    exit 1; \
+	fi
 
 # all _m.h files must exist before we build anything, so run opp_msgc first
 subdirs $(OBJS) : generateheaders
